---
version: "3"

services:
  community:
    image: labkey/community
    container_name: ${IDENT:-labkey}
    # build: {"context": ".", "args": ["LABKEY_VERSION=21.3-SNAPSHOT"]}
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 1024M
    depends_on:
      - pg-community
      # - mailhog
    ports:
      - ${HOST_PORT:-8443}:8443
    volumes:
      - ./mounts/files:/labkey/files
      # - files:/labkey/files
      - ./mounts/modules:/labkey/externalModules
      - ./mounts/logs:/labkey/logs
    environment:
      # - DEBUG=1

      # - LABKEY_SYSTEM_SHORT_NAME=Sirius Cybernetics Corporation
      # - LABKEY_COMPANY_NAME=Sirius Cybernetics Corporation
      # - LABKEY_SYSTEM_DESCRIPTION=Sirius Cybernetics Corporation

      # - TOMCAT_ENABLE_ACCESS_LOG=1
      - LOG_LEVEL_SPRING_WEB=INFO
      - LOG_LEVEL_TOMCAT=DEBUG
      - LOG_LEVEL_DEFAULT=DEBUG
      - LOG_LEVEL_LABKEY_DEFAULT=DEBUG
      - LOG_LEVEL_API_SETTINGS=DEBUG
      - LOG_LEVEL_API_MODULELOADER=DEBUG

      - LOGGER_PATTERN=%-80.80logger{79}

      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-a"placeholder#'password}
      - POSTGRES_HOST=pg-community

      - MAX_JVM_RAM_PERCENT=75.0
      - JAVA_PRE_JAR_EXTRA=-XX:+UseSerialGC -Xss512k

      # - SMTP_HOST=mailhog
      # - SMTP_PORT=1025

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_AUTH=true
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_STARTTLS=true

      - LABKEY_SYSTEM_EMAIL_ADDRESS=${SMTP_FROM}
      # - SMTP_FROM=

      # uncomment to enable CAS against labkey.org
      # - |
      #   LABKEY_STARTUP_BASIC_EXTRA='
      #     CasAuthenticationProperties.ServerURL;startup = https://www.labkey.org/cas
      #     CasAuthenticationProperties.AutoRedirect;startup = true
      #     CasAuthenticationProperties.InvokeLogout;startup = true
      #     CasAuthenticationProperties.Description;startup = configured_by_docker_compose
      #     SiteSettings.experimentalFeature.disableGuestAccount = TRUE
      #     UserRoles.${LABKEY_ACCOUNT_EMAIL} = org.labkey.api.security.roles.SiteAdminRole
      #   '
      # - LABKEY_STARTUP_DISTRIBUTION_EXTRA=

      # If these parameters are set or set to null use provided; else set values to create initial user
      - LABKEY_CREATE_INITIAL_USER=${LABKEY_CREATE_INITIAL_USER-1}
      - LABKEY_CREATE_INITIAL_USER_APIKEY=${LABKEY_CREATE_INITIAL_USER_APIKEY-1}

      - POSTGRES_MAX_TOTAL_CONNECTIONS=${POSTGRES_MAX_TOTAL_CONNECTIONS:-50}
      - POSTGRES_MAX_IDLE_CONNECTIONS=${POSTGRES_MAX_IDLE_CONNECTIONS:-10}
      - POSTGRES_MAX_WAIT_MILLIS=${POSTGRES_MAX_WAIT_MILLIS:-120000}
      - POSTGRES_ACCESS_UNDERLYING_CONNECTIONS=${POSTGRES_ACCESS_UNDERLYING_CONNECTIONS:-true}
      - POSTGRES_VALIDATION_QUERY=${POSTGRES_VALIDATION_QUERY:-SELECT 1}

      - LABKEY_CUSTOM_PROPERTIES_S3_URI=${LABKEY_CUSTOM_PROPERTIES_S3_URI}
      - LABKEY_DEFAULT_PROPERTIES_S3_URI=${LABKEY_DEFAULT_PROPERTIES_S3_URI}
      - LOG4J_CONFIG_FILE=${LOG4J_CONFIG_FILE-log4j2.xml}
      - JSON_OUTPUT=${JSON_OUTPUT-false}      
      - SLEEP=${SLEEP:-0}

  pg-community:
    image: postgres:13
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: 512M
    # silent postgres w/o needing to remake the container!
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "docker-entrypoint.sh postgres >/dev/null 2>&1"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-a"placeholder#'password}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./pgdata/postgres-data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT:-54321}:5432


# below are for internal LabKey testing
  allpg:
    image: ${COMPOSE_IMAGE:-labkey/community}
    container_name: ${IDENT:-allpg}
    # build: {"context": ".", "args": ["LABKEY_VERSION=21.3-SNAPSHOT"]}
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 1024M
    depends_on:
      - pg-allpg
      # - mailhog
    ports:
      - ${HOST_PORT:-8443}:8443
    volumes:
      - ./mounts/files:/labkey/files
      # - files:/labkey/files
      - ./mounts/modules:/labkey/externalModules
      - ./mounts/logs:/labkey/logs
    environment:
      # - DEBUG=1

      # - LABKEY_SYSTEM_SHORT_NAME=Sirius Cybernetics Corporation
      # - LABKEY_COMPANY_NAME=Sirius Cybernetics Corporation
      # - LABKEY_SYSTEM_DESCRIPTION=Sirius Cybernetics Corporation

      # - TOMCAT_ENABLE_ACCESS_LOG=1
      - LOG_LEVEL_SPRING_WEB=INFO
      - LOG_LEVEL_TOMCAT=DEBUG
      - LOG_LEVEL_DEFAULT=DEBUG
      - LOG_LEVEL_LABKEY_DEFAULT=DEBUG
      - LOG_LEVEL_API_SETTINGS=DEBUG
      - LOG_LEVEL_API_MODULELOADER=DEBUG

      - LOGGER_PATTERN=%-80.80logger{79}

      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-a"placeholder#'password}
      - POSTGRES_HOST=pg-allpg

      - MAX_JVM_RAM_PERCENT=75.0
      - JAVA_PRE_JAR_EXTRA=-XX:+UseSerialGC -Xss512k

      # - SMTP_HOST=mailhog
      # - SMTP_PORT=1025

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_AUTH=true
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_STARTTLS=true

      - LABKEY_SYSTEM_EMAIL_ADDRESS=${SMTP_FROM}
      # - SMTP_FROM=

      # uncomment to enable CAS against labkey.org
      # - |
      #   LABKEY_STARTUP_BASIC_EXTRA='
      #     CasAuthenticationProperties.ServerURL;startup = https://www.labkey.org/cas
      #     CasAuthenticationProperties.AutoRedirect;startup = true
      #     CasAuthenticationProperties.InvokeLogout;startup = true
      #     CasAuthenticationProperties.Description;startup = configured_by_docker_compose
      #     SiteSettings.experimentalFeature.disableGuestAccount = TRUE
      #     UserRoles.${LABKEY_ACCOUNT_EMAIL} = org.labkey.api.security.roles.SiteAdminRole
      #   '
      # - LABKEY_STARTUP_DISTRIBUTION_EXTRA=

      # If these parameters are set or set to null use provided; else set values to create initial user
      - LABKEY_CREATE_INITIAL_USER=${LABKEY_CREATE_INITIAL_USER-1}
      - LABKEY_CREATE_INITIAL_USER_APIKEY=${LABKEY_CREATE_INITIAL_USER_APIKEY-1}

      - POSTGRES_MAX_TOTAL_CONNECTIONS=${POSTGRES_MAX_TOTAL_CONNECTIONS:-50}
      - POSTGRES_MAX_IDLE_CONNECTIONS=${POSTGRES_MAX_IDLE_CONNECTIONS:-10}
      - POSTGRES_MAX_WAIT_MILLIS=${POSTGRES_MAX_WAIT_MILLIS:-120000}
      - POSTGRES_ACCESS_UNDERLYING_CONNECTIONS=${POSTGRES_ACCESS_UNDERLYING_CONNECTIONS:-true}
      - POSTGRES_VALIDATION_QUERY=${POSTGRES_VALIDATION_QUERY:-SELECT 1}

      - LABKEY_CUSTOM_PROPERTIES_S3_URI=${LABKEY_CUSTOM_PROPERTIES_S3_URI}
      - LABKEY_DEFAULT_PROPERTIES_S3_URI=${LABKEY_DEFAULT_PROPERTIES_S3_URI}
      - LOG4J_CONFIG_FILE=${LOG4J_CONFIG_FILE-log4j2.xml}
      - JSON_OUTPUT=${JSON_OUTPUT-false}      
      - SLEEP=${SLEEP:-0}

  pg-allpg:
    image: postgres:13
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: 512M
    # silent postgres w/o needing to remake the container!
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "docker-entrypoint.sh postgres >/dev/null 2>&1"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-a"placeholder#'password}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./pgdata/${IDENT:-postgres}-data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT:-54321}:5432

  enterprise:
    image: ${COMPOSE_IMAGE:-labkey/community}
    container_name: ${IDENT:-enterprise}
    # build: {"context": ".", "args": ["LABKEY_VERSION=21.3-SNAPSHOT"]}
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 1024M
    depends_on:
      - pg-enterprise
      # - mailhog
    ports:
      - ${HOST_PORT:-8443}:8443
    volumes:
      - ./mounts/files:/labkey/files
      # - files:/labkey/files
      - ./mounts/modules:/labkey/externalModules
      - ./mounts/logs:/labkey/logs
    environment:
      # - DEBUG=1

      # - LABKEY_SYSTEM_SHORT_NAME=Sirius Cybernetics Corporation
      # - LABKEY_COMPANY_NAME=Sirius Cybernetics Corporation
      # - LABKEY_SYSTEM_DESCRIPTION=Sirius Cybernetics Corporation

      # - TOMCAT_ENABLE_ACCESS_LOG=1
      - LOG_LEVEL_SPRING_WEB=INFO
      - LOG_LEVEL_TOMCAT=DEBUG
      - LOG_LEVEL_DEFAULT=DEBUG
      - LOG_LEVEL_LABKEY_DEFAULT=DEBUG
      - LOG_LEVEL_API_SETTINGS=DEBUG
      - LOG_LEVEL_API_MODULELOADER=DEBUG

      - LOGGER_PATTERN=%-80.80logger{79}

      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-a"placeholder#'password}
      - POSTGRES_HOST=pg-enterprise

      - MAX_JVM_RAM_PERCENT=75.0
      - JAVA_PRE_JAR_EXTRA=-XX:+UseSerialGC -Xss512k

      # - SMTP_HOST=mailhog
      # - SMTP_PORT=1025

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_AUTH=true
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_STARTTLS=true

      - LABKEY_SYSTEM_EMAIL_ADDRESS=${SMTP_FROM}
      # - SMTP_FROM=

      # uncomment to enable CAS against labkey.org
      # - |
      #   LABKEY_STARTUP_BASIC_EXTRA='
      #     CasAuthenticationProperties.ServerURL;startup = https://www.labkey.org/cas
      #     CasAuthenticationProperties.AutoRedirect;startup = true
      #     CasAuthenticationProperties.InvokeLogout;startup = true
      #     CasAuthenticationProperties.Description;startup = configured_by_docker_compose
      #     SiteSettings.experimentalFeature.disableGuestAccount = TRUE
      #     UserRoles.${LABKEY_ACCOUNT_EMAIL} = org.labkey.api.security.roles.SiteAdminRole
      #   '
      # - LABKEY_STARTUP_DISTRIBUTION_EXTRA=

      # If these parameters are set or set to null use provided; else set values to create initial user
      - LABKEY_CREATE_INITIAL_USER=${LABKEY_CREATE_INITIAL_USER-1}
      - LABKEY_CREATE_INITIAL_USER_APIKEY=${LABKEY_CREATE_INITIAL_USER_APIKEY-1}

      - POSTGRES_MAX_TOTAL_CONNECTIONS=${POSTGRES_MAX_TOTAL_CONNECTIONS:-50}
      - POSTGRES_MAX_IDLE_CONNECTIONS=${POSTGRES_MAX_IDLE_CONNECTIONS:-10}
      - POSTGRES_MAX_WAIT_MILLIS=${POSTGRES_MAX_WAIT_MILLIS:-120000}
      - POSTGRES_ACCESS_UNDERLYING_CONNECTIONS=${POSTGRES_ACCESS_UNDERLYING_CONNECTIONS:-true}
      - POSTGRES_VALIDATION_QUERY=${POSTGRES_VALIDATION_QUERY:-SELECT 1}

      - LABKEY_CUSTOM_PROPERTIES_S3_URI=${LABKEY_CUSTOM_PROPERTIES_S3_URI}
      - LABKEY_DEFAULT_PROPERTIES_S3_URI=${LABKEY_DEFAULT_PROPERTIES_S3_URI}
      - LOG4J_CONFIG_FILE=${LOG4J_CONFIG_FILE-log4j2.xml}
      - JSON_OUTPUT=${JSON_OUTPUT-false}      
      - SLEEP=${SLEEP:-0}

  pg-enterprise:
    image: postgres:13
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: 512M
    # silent postgres w/o needing to remake the container!
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "docker-entrypoint.sh postgres >/dev/null 2>&1"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-a"placeholder#'password}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./pgdata/${IDENT:-postgres}-data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT:-54321}:5432

  lims_starter:
    image: ${COMPOSE_IMAGE:-labkey/community}
    container_name: ${IDENT:-lims_starter}
    # build: {"context": ".", "args": ["LABKEY_VERSION=21.3-SNAPSHOT"]}
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 1024M
    depends_on:
      - pg-lims_starter
      # - mailhog
    ports:
      - ${HOST_PORT:-8443}:8443
    volumes:
      - ./mounts/files:/labkey/files
      # - files:/labkey/files
      - ./mounts/modules:/labkey/externalModules
      - ./mounts/logs:/labkey/logs
    environment:
      # - DEBUG=1

      # - LABKEY_SYSTEM_SHORT_NAME=Sirius Cybernetics Corporation
      # - LABKEY_COMPANY_NAME=Sirius Cybernetics Corporation
      # - LABKEY_SYSTEM_DESCRIPTION=Sirius Cybernetics Corporation

      # - TOMCAT_ENABLE_ACCESS_LOG=1
      - LOG_LEVEL_SPRING_WEB=INFO
      - LOG_LEVEL_TOMCAT=DEBUG
      - LOG_LEVEL_DEFAULT=DEBUG
      - LOG_LEVEL_LABKEY_DEFAULT=DEBUG
      - LOG_LEVEL_API_SETTINGS=DEBUG
      - LOG_LEVEL_API_MODULELOADER=DEBUG

      - LOGGER_PATTERN=%-80.80logger{79}

      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-a"placeholder#'password}
      - POSTGRES_HOST=pg-lims_starter

      - MAX_JVM_RAM_PERCENT=75.0
      - JAVA_PRE_JAR_EXTRA=-XX:+UseSerialGC -Xss512k

      # - SMTP_HOST=mailhog
      # - SMTP_PORT=1025

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_AUTH=true
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_STARTTLS=true

      - LABKEY_SYSTEM_EMAIL_ADDRESS=${SMTP_FROM}
      # - SMTP_FROM=

      # uncomment to enable CAS against labkey.org
      # - |
      #   LABKEY_STARTUP_BASIC_EXTRA='
      #     CasAuthenticationProperties.ServerURL;startup = https://www.labkey.org/cas
      #     CasAuthenticationProperties.AutoRedirect;startup = true
      #     CasAuthenticationProperties.InvokeLogout;startup = true
      #     CasAuthenticationProperties.Description;startup = configured_by_docker_compose
      #     SiteSettings.experimentalFeature.disableGuestAccount = TRUE
      #     UserRoles.${LABKEY_ACCOUNT_EMAIL} = org.labkey.api.security.roles.SiteAdminRole
      #   '
      # - LABKEY_STARTUP_DISTRIBUTION_EXTRA=

      # If these parameters are set or set to null use provided; else set values to create initial user
      - LABKEY_CREATE_INITIAL_USER=${LABKEY_CREATE_INITIAL_USER-1}
      - LABKEY_CREATE_INITIAL_USER_APIKEY=${LABKEY_CREATE_INITIAL_USER_APIKEY-1}

      - POSTGRES_MAX_TOTAL_CONNECTIONS=${POSTGRES_MAX_TOTAL_CONNECTIONS:-50}
      - POSTGRES_MAX_IDLE_CONNECTIONS=${POSTGRES_MAX_IDLE_CONNECTIONS:-10}
      - POSTGRES_MAX_WAIT_MILLIS=${POSTGRES_MAX_WAIT_MILLIS:-120000}
      - POSTGRES_ACCESS_UNDERLYING_CONNECTIONS=${POSTGRES_ACCESS_UNDERLYING_CONNECTIONS:-true}
      - POSTGRES_VALIDATION_QUERY=${POSTGRES_VALIDATION_QUERY:-SELECT 1}

      - LABKEY_CUSTOM_PROPERTIES_S3_URI=${LABKEY_CUSTOM_PROPERTIES_S3_URI}
      - LABKEY_DEFAULT_PROPERTIES_S3_URI=${LABKEY_DEFAULT_PROPERTIES_S3_URI}
      - LOG4J_CONFIG_FILE=${LOG4J_CONFIG_FILE-log4j2.xml}
      - JSON_OUTPUT=${JSON_OUTPUT-false}
      - SLEEP=${SLEEP:-0}

  pg-lims_starter:
    image: postgres:13
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: 512M
    # silent postgres w/o needing to remake the container!
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "docker-entrypoint.sh postgres >/dev/null 2>&1"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-a"placeholder#'password}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./pgdata/${IDENT:-postgres}-data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT:-54321}:5432


# below can optionally be added to services above as needed

  # mailhog:
  #   container_name: mailhog
  #   image: mailhog/mailhog
  #   logging:
  #     driver: 'none'  # disable saving logs
  #   ports:
  #     - 1025:1025 # smtp server
  #     - 8025:8025 # web ui

  # restic:
  #   container_name: restic
  #   image: restic/restic
  #   depends_on:
  #     - labkey
  #     - minio
  #   environment:
  #     - AWS_ACCESS_KEY_ID=placeholder
  #     - AWS_SECRET_ACCESS_KEY=placeholder
  #     - RESTIC_PASSWORD_COMMAND=echo placeholder
  #     - RESTIC_REPOSITORY=s3:http://minio:9000/backup
  #   volumes:
  #     - files:/backup
  #   entrypoint: /bin/sh
  #   command:
  #     - -x
  #     - -c
  #     - 'restic init; while true; do restic backup /backup || exit 1; sleep 60; done'

  # minio:
  #   container_name: minio
  #   image: minio/minio
  #   environment:
  #     - MINIO_ROOT_USER=placeholder
  #     - MINIO_ROOT_PASSWORD=placeholder
  #   command:
  #     - server
  #     - /data
  #   volumes:
  #     - ./mounts/backups:/data

# volumes:
#   files:
