name: dockle

on:
  push:
    branches:
      - fb_*

  pull_request:
    branches:
      - develop

jobs:
  dockle:
    name: dockle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build an image from Dockerfile
        run: |
          LABKEY_VERSION=HelloWorld make build
      - name: Run dockle
        uses: goodwithtech/dockle-action@0.1.0
        env:
          DOCKER_CONTENT_TRUST: 0
        with:
          image: 'labkey/community:helloworld'
          format: 'list'
          exit-code: '1'
          exit-level: 'warn'
          ignore: 'CIS-DI-0009,CIS-DI-0010'
  xeol:
    name: xeol
    needs: dockle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: xeol-dir
        uses: noqcks/xeol-action@v1.0.6
        with:
          path: "."
      - name: xeol-image
        uses: noqcks/xeol-action@v1.0.6
        with:
          # created by 'dockle' job above
          image: "labkey/community:helloworld"
