name: hadolint

on:
  push:
    branches:
      - fb_*
      - '*_fb_*'

  pull_request:
    branches:
      - develop
      - 'release*'

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
